#! /usr/bin/env php

<?php

use DumpCrawler\CleanCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Dump-Crawler', 1.1);

$app->add(new CleanCommand);
$app->run();
